# proxy port
port = 8086

# API path to get hyperBlock from covalent proxy
hyperBlockPath = "/hyperblock"

# API path to get hyperBlocks from covalent proxy
hyperBlocksPath = "/hyperblocks"

# When fetching multiple hyperblocks, requests will be grouped in hyperBlocksBatchSize and parallelized
hyperBlocksBatchSize = 20

# multiversxProxyUrl url used to fetch hyperBlocks from Multiversx; e.g.: https://gateway.multiversx.com for mainnet
multiversxProxyUrl = "https://gateway.multiversx.com"

# requestTimeoutSec represents the maximum number of seconds a request can last until throwing an error
# A Timeout of zero means no timeout.
requestTimeOutSec = 80

[hyperBlockQueryOptions]
    # hyper block query parameter for Multiversx proxy to fetch logs
    withLogs = true

    # hyper block query parameter for Multiversx proxy to fetch altered accounts
    withAlteredAccounts = true

    # hyper block query parameter for Multiversx proxy to fetch hyper blocks notarized at source
    notarizedAtSource = true

    # hyper block query parameter for Multiversx proxy to fetch all tokens in altered accounts
    tokens = "all"
