# Proxy port
Port = 8086

# API path to get hyperBlock from covalent proxy
HyperBlockPath = "/hyperBlock"


# ElrondProxyUrl url used to fetch hyperBlocks from Elrond; e.g.: https://gateway.elrond.com for mainnet
ElrondProxyUrl = "https://gateway.elrond.com"
